### ISSUE TITLE
ダークモードメディアクエリへの対応

### ISSUE THREAD

**Issue by qrac** [qrac/stylus-dashi#1]
- [How to get dark mode working with CSS – freeCodeCamp.org](https://medium.freecodecamp.org/how-to-get-dark-mode-working-with-css-740ad31e22e)

```css
root: {
  --text-color: DarkBlue;
  --back-color: Azure;
}

body { color: var(--text-color); background: var(--back-color)}

@media (prefers-dark-interface) {
  root: {
   --text-color: Azure;
   --back-color: DarkBlue;
  } 
}
```
